### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../run_Trans_50x_50d_news/test_emb_20.txt'

### ISSUE THREAD

**Issue by WxZy530** [wenlinyao/EMNLP20-SubeventAcquisition#1]
When using the example in readme，
FileNotFoundError: [Errno 2] No such file or directory:'../run_Trans_50x_50d_news/test_emb_20.txt'，
this problem comes out.
Could you tell what is in this file，and how to acquire？Appreciate to your attention.

**Comment by wenlinyao** [comment]
Hi, test_emb_20.txt storages vector representation of all event phrases that will be used in evaluation datasets (RED, Timebank, etc.). Each line is the vector representation of one event phrase. Please use the TransE model in model_Trans/ to generate this file.

**Comment by WxZy530** [comment]
Thanks about your reply,but here comes another problem.When trainning the LSTM_context_model_main.py,"../annotation/valid_pairs_v3.txt"this file is missing,is there another program needs to run first?
Besides,I try to use model/extract_event_pair.py, it seems needs some files in "\run_extract_sentences_nmod2\news ",whose format is like:"<doc_id> \<subevent>\<word>"

BTW,if it's possible,maybe an order of running this project will solve above problems : )

**Comment by wenlinyao** [comment]
Hi, sorry for the confusion. I have fixed the file path of LSTM_context_model_main.py in model_Trans/. It should take all acquired subevent knowledge as the input and then train a TransE model.

**Comment by WxZy530** [comment]
Sorry to bother again,with your help I have already evluate the context Bert model.But I still get several problems.
Q1: Since this work is very valuable to learn,I was trying to train the weakly supervised model from scratch.But files and packages for candidate_pairs are missing(e.g.:"run_extract_event_pair_conj2","run_extract_event_pair_nmod2") in "distant_context_model /BERT_context_model_main.py".Could you tell the way to construct these files?: )
Q2: Besides,there is a confusion of my own,I try to ,I apply the "temporal_event_pair" to construct the "test_emb_20.txt" in model_Trans,then apply it to the "context_BERT_model" to evaluate the temporal pairs,is this the right way?But the result is not as good as evaluating  the subevent paris.
Q3: In the appendix A of your paper,you describe the event pepresentations,is this part in your code?

**Comment by wenlinyao** [comment]
Sorry that I just saw your question. 
Q1: Those two files are some intermediate files that are too big to upload to github. I remember the two files store event pair co-occurrence with prep patterns.
Q2: My paper uses subevent knowledge to construct "test_emb_20.txt" file instead of using temporal pairs.
Q3: Yeah, they are included the utilities.py code file.
